The new version of traceur (0.5.101) results in DECRYP EROORS for evey message for FFOS: DECRYPT ERROR,TypeError: $traceurRuntime.toProperty is not a function.
This is V0.0.83 from Loqui 0.5.10 that is working fine for FFOS.

Is there any need to update for UT?